// Copyright Dirk Lemstra https://github.com/dlemstra/Magick.NET.
// Licensed under the Apache License, Version 2.0.
// <auto-generated/>
#nullable enable

using System;
using System.Security;
using System.Runtime.InteropServices;

#if Q8
using QuantumType = System.Byte;
#elif Q16
using QuantumType = System.UInt16;
#elif Q16HDRI
using QuantumType = System.Single;
#else
#error Not implemented!
#endif

namespace ImageMagick;

public partial class MagickSettings
{
    [SuppressUnmanagedCodeSecurity]
    private static unsafe class NativeMethods
    {
        #if PLATFORM_x64 || PLATFORM_AnyCPU
        public static class X64
        {
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_Create();
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Dispose(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.Bool)]
            public static extern bool MagickSettings_AntiAlias_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_AntiAlias_Set(IntPtr instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_BackgroundColor_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_BackgroundColor_Set(IntPtr instance, IntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_ColorSpace_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_ColorSpace_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_ColorType_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_ColorType_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_Compression_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Compression_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.Bool)]
            public static extern bool MagickSettings_Debug_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Debug_Set(IntPtr instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_Density_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Density_Set(IntPtr instance, IntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_Depth_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Depth_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_Endian_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Endian_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_Extract_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Extract_Set(IntPtr instance, IntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_Format_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Format_Set(IntPtr instance, IntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern double MagickSettings_FontPointsize_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_FontPointsize_Set(IntPtr instance, double value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.Bool)]
            public static extern bool MagickSettings_Monochrome_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Monochrome_Set(IntPtr instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_Interlace_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Interlace_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.Bool)]
            public static extern bool MagickSettings_Verbose_Get(IntPtr instance);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Verbose_Set(IntPtr instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetColorFuzz(IntPtr Instance, double value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetFileName(IntPtr Instance, IntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_SetFont(IntPtr Instance, IntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetNumberScenes(IntPtr Instance, UIntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetOption(IntPtr Instance, IntPtr key, IntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetPage(IntPtr Instance, IntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetPing(IntPtr Instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetQuality(IntPtr Instance, UIntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetScenes(IntPtr Instance, IntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetScene(IntPtr Instance, UIntPtr value);
            [DllImport(NativeLibrary.X64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetSize(IntPtr Instance, IntPtr value);
        }
        #endif
        #if PLATFORM_arm64 || PLATFORM_AnyCPU
        public static class ARM64
        {
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_Create();
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Dispose(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.Bool)]
            public static extern bool MagickSettings_AntiAlias_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_AntiAlias_Set(IntPtr instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_BackgroundColor_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_BackgroundColor_Set(IntPtr instance, IntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_ColorSpace_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_ColorSpace_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_ColorType_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_ColorType_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_Compression_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Compression_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.Bool)]
            public static extern bool MagickSettings_Debug_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Debug_Set(IntPtr instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_Density_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Density_Set(IntPtr instance, IntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_Depth_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Depth_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_Endian_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Endian_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_Extract_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Extract_Set(IntPtr instance, IntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_Format_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Format_Set(IntPtr instance, IntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern double MagickSettings_FontPointsize_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_FontPointsize_Set(IntPtr instance, double value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.Bool)]
            public static extern bool MagickSettings_Monochrome_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Monochrome_Set(IntPtr instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_Interlace_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Interlace_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.Bool)]
            public static extern bool MagickSettings_Verbose_Get(IntPtr instance);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Verbose_Set(IntPtr instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetColorFuzz(IntPtr Instance, double value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetFileName(IntPtr Instance, IntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_SetFont(IntPtr Instance, IntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetNumberScenes(IntPtr Instance, UIntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetOption(IntPtr Instance, IntPtr key, IntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetPage(IntPtr Instance, IntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetPing(IntPtr Instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetQuality(IntPtr Instance, UIntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetScenes(IntPtr Instance, IntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetScene(IntPtr Instance, UIntPtr value);
            [DllImport(NativeLibrary.ARM64Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetSize(IntPtr Instance, IntPtr value);
        }
        #endif
        #if PLATFORM_x86 || PLATFORM_AnyCPU
        public static class X86
        {
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_Create();
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Dispose(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.Bool)]
            public static extern bool MagickSettings_AntiAlias_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_AntiAlias_Set(IntPtr instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_BackgroundColor_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_BackgroundColor_Set(IntPtr instance, IntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_ColorSpace_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_ColorSpace_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_ColorType_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_ColorType_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_Compression_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Compression_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.Bool)]
            public static extern bool MagickSettings_Debug_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Debug_Set(IntPtr instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_Density_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Density_Set(IntPtr instance, IntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_Depth_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Depth_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_Endian_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Endian_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_Extract_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Extract_Set(IntPtr instance, IntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_Format_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Format_Set(IntPtr instance, IntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern double MagickSettings_FontPointsize_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_FontPointsize_Set(IntPtr instance, double value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.Bool)]
            public static extern bool MagickSettings_Monochrome_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Monochrome_Set(IntPtr instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern UIntPtr MagickSettings_Interlace_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Interlace_Set(IntPtr instance, UIntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            [return: MarshalAs(UnmanagedType.Bool)]
            public static extern bool MagickSettings_Verbose_Get(IntPtr instance);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_Verbose_Set(IntPtr instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetColorFuzz(IntPtr Instance, double value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetFileName(IntPtr Instance, IntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr MagickSettings_SetFont(IntPtr Instance, IntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetNumberScenes(IntPtr Instance, UIntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetOption(IntPtr Instance, IntPtr key, IntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetPage(IntPtr Instance, IntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetPing(IntPtr Instance, [MarshalAs(UnmanagedType.Bool)] bool value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetQuality(IntPtr Instance, UIntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetScenes(IntPtr Instance, IntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetScene(IntPtr Instance, UIntPtr value);
            [DllImport(NativeLibrary.X86Name, CallingConvention = CallingConvention.Cdecl)]
            public static extern void MagickSettings_SetSize(IntPtr Instance, IntPtr value);
        }
        #endif
    }
    private unsafe sealed partial class NativeMagickSettings : NativeInstance
    {
        static NativeMagickSettings() { Environment.Initialize(); }
        protected override void Dispose(IntPtr instance)
        {
            #if PLATFORM_AnyCPU
            if (Runtime.IsArm64)
            #endif
            #if PLATFORM_arm64 || PLATFORM_AnyCPU
            NativeMethods.ARM64.MagickSettings_Dispose(instance);
            #endif
            #if PLATFORM_AnyCPU
            else if (Runtime.Is64Bit)
            #endif
            #if PLATFORM_x64 || PLATFORM_AnyCPU
            NativeMethods.X64.MagickSettings_Dispose(instance);
            #endif
            #if PLATFORM_AnyCPU
            else
            #endif
            #if PLATFORM_x86 || PLATFORM_AnyCPU
            NativeMethods.X86.MagickSettings_Dispose(instance);
            #endif
        }
        public NativeMagickSettings()
        {
            #if PLATFORM_AnyCPU
            if (Runtime.IsArm64)
            #endif
            #if PLATFORM_arm64 || PLATFORM_AnyCPU
            Instance = NativeMethods.ARM64.MagickSettings_Create();
            #endif
            #if PLATFORM_AnyCPU
            else if (Runtime.Is64Bit)
            #endif
            #if PLATFORM_x64 || PLATFORM_AnyCPU
            Instance = NativeMethods.X64.MagickSettings_Create();
            #endif
            #if PLATFORM_AnyCPU
            else
            #endif
            #if PLATFORM_x86 || PLATFORM_AnyCPU
            Instance = NativeMethods.X86.MagickSettings_Create();
            #endif
            if (Instance == IntPtr.Zero)
                throw new InvalidOperationException();
        }
        protected override string TypeName
        {
            get
            {
                return nameof(MagickSettings);
            }
        }
        public bool AntiAlias
        {
            get
            {
                bool result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_AntiAlias_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_AntiAlias_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_AntiAlias_Get(Instance);
                #endif
                return result;
            }
            set
            {
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_AntiAlias_Set(Instance, value);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_AntiAlias_Set(Instance, value);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_AntiAlias_Set(Instance, value);
                #endif
            }
        }
        public IMagickColor<QuantumType>? BackgroundColor
        {
            get
            {
                IntPtr result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_BackgroundColor_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_BackgroundColor_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_BackgroundColor_Get(Instance);
                #endif
                return MagickColor.CreateInstance(result);
            }
            set
            {
                using var valueNative = MagickColor.CreateInstance(value);
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_BackgroundColor_Set(Instance, valueNative.Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_BackgroundColor_Set(Instance, valueNative.Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_BackgroundColor_Set(Instance, valueNative.Instance);
                #endif
            }
        }
        public ColorSpace ColorSpace
        {
            get
            {
                UIntPtr result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_ColorSpace_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_ColorSpace_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_ColorSpace_Get(Instance);
                #endif
                return (ColorSpace)result;
            }
            set
            {
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_ColorSpace_Set(Instance, (UIntPtr)value);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_ColorSpace_Set(Instance, (UIntPtr)value);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_ColorSpace_Set(Instance, (UIntPtr)value);
                #endif
            }
        }
        public ColorType ColorType
        {
            get
            {
                UIntPtr result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_ColorType_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_ColorType_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_ColorType_Get(Instance);
                #endif
                return (ColorType)result;
            }
            set
            {
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_ColorType_Set(Instance, (UIntPtr)value);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_ColorType_Set(Instance, (UIntPtr)value);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_ColorType_Set(Instance, (UIntPtr)value);
                #endif
            }
        }
        public CompressionMethod Compression
        {
            get
            {
                UIntPtr result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_Compression_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_Compression_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_Compression_Get(Instance);
                #endif
                return (CompressionMethod)result;
            }
            set
            {
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_Compression_Set(Instance, (UIntPtr)value);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_Compression_Set(Instance, (UIntPtr)value);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_Compression_Set(Instance, (UIntPtr)value);
                #endif
            }
        }
        public bool Debug
        {
            get
            {
                bool result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_Debug_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_Debug_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_Debug_Get(Instance);
                #endif
                return result;
            }
            set
            {
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_Debug_Set(Instance, value);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_Debug_Set(Instance, value);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_Debug_Set(Instance, value);
                #endif
            }
        }
        public string? Density
        {
            get
            {
                IntPtr result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_Density_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_Density_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_Density_Get(Instance);
                #endif
                return UTF8Marshaler.NativeToManagedNullable(result);
            }
            set
            {
                using var valueNative = UTF8Marshaler.CreateInstance(value);
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_Density_Set(Instance, valueNative.Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_Density_Set(Instance, valueNative.Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_Density_Set(Instance, valueNative.Instance);
                #endif
            }
        }
        public int Depth
        {
            get
            {
                UIntPtr result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_Depth_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_Depth_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_Depth_Get(Instance);
                #endif
                return (int)result;
            }
            set
            {
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_Depth_Set(Instance, (UIntPtr)value);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_Depth_Set(Instance, (UIntPtr)value);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_Depth_Set(Instance, (UIntPtr)value);
                #endif
            }
        }
        public Endian Endian
        {
            get
            {
                UIntPtr result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_Endian_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_Endian_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_Endian_Get(Instance);
                #endif
                return (Endian)result;
            }
            set
            {
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_Endian_Set(Instance, (UIntPtr)value);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_Endian_Set(Instance, (UIntPtr)value);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_Endian_Set(Instance, (UIntPtr)value);
                #endif
            }
        }
        public string? Extract
        {
            get
            {
                IntPtr result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_Extract_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_Extract_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_Extract_Get(Instance);
                #endif
                return UTF8Marshaler.NativeToManagedNullable(result);
            }
            set
            {
                using var valueNative = UTF8Marshaler.CreateInstance(value);
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_Extract_Set(Instance, valueNative.Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_Extract_Set(Instance, valueNative.Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_Extract_Set(Instance, valueNative.Instance);
                #endif
            }
        }
        public string? Format
        {
            get
            {
                IntPtr result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_Format_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_Format_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_Format_Get(Instance);
                #endif
                return UTF8Marshaler.NativeToManagedNullable(result);
            }
            set
            {
                using var valueNative = UTF8Marshaler.CreateInstance(value);
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_Format_Set(Instance, valueNative.Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_Format_Set(Instance, valueNative.Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_Format_Set(Instance, valueNative.Instance);
                #endif
            }
        }
        public double FontPointsize
        {
            get
            {
                double result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_FontPointsize_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_FontPointsize_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_FontPointsize_Get(Instance);
                #endif
                return result;
            }
            set
            {
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_FontPointsize_Set(Instance, value);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_FontPointsize_Set(Instance, value);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_FontPointsize_Set(Instance, value);
                #endif
            }
        }
        public bool Monochrome
        {
            get
            {
                bool result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_Monochrome_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_Monochrome_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_Monochrome_Get(Instance);
                #endif
                return result;
            }
            set
            {
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_Monochrome_Set(Instance, value);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_Monochrome_Set(Instance, value);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_Monochrome_Set(Instance, value);
                #endif
            }
        }
        public Interlace Interlace
        {
            get
            {
                UIntPtr result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_Interlace_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_Interlace_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_Interlace_Get(Instance);
                #endif
                return (Interlace)result;
            }
            set
            {
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_Interlace_Set(Instance, (UIntPtr)value);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_Interlace_Set(Instance, (UIntPtr)value);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_Interlace_Set(Instance, (UIntPtr)value);
                #endif
            }
        }
        public bool Verbose
        {
            get
            {
                bool result;
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                result = NativeMethods.ARM64.MagickSettings_Verbose_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                result = NativeMethods.X64.MagickSettings_Verbose_Get(Instance);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                result = NativeMethods.X86.MagickSettings_Verbose_Get(Instance);
                #endif
                return result;
            }
            set
            {
                #if PLATFORM_AnyCPU
                if (Runtime.IsArm64)
                #endif
                #if PLATFORM_arm64 || PLATFORM_AnyCPU
                NativeMethods.ARM64.MagickSettings_Verbose_Set(Instance, value);
                #endif
                #if PLATFORM_AnyCPU
                else if (Runtime.Is64Bit)
                #endif
                #if PLATFORM_x64 || PLATFORM_AnyCPU
                NativeMethods.X64.MagickSettings_Verbose_Set(Instance, value);
                #endif
                #if PLATFORM_AnyCPU
                else
                #endif
                #if PLATFORM_x86 || PLATFORM_AnyCPU
                NativeMethods.X86.MagickSettings_Verbose_Set(Instance, value);
                #endif
            }
        }
        public void SetColorFuzz(double value)
        {
            #if PLATFORM_AnyCPU
            if (Runtime.IsArm64)
            #endif
            #if PLATFORM_arm64 || PLATFORM_AnyCPU
            NativeMethods.ARM64.MagickSettings_SetColorFuzz(Instance, value);
            #endif
            #if PLATFORM_AnyCPU
            else if (Runtime.Is64Bit)
            #endif
            #if PLATFORM_x64 || PLATFORM_AnyCPU
            NativeMethods.X64.MagickSettings_SetColorFuzz(Instance, value);
            #endif
            #if PLATFORM_AnyCPU
            else
            #endif
            #if PLATFORM_x86 || PLATFORM_AnyCPU
            NativeMethods.X86.MagickSettings_SetColorFuzz(Instance, value);
            #endif
        }
        public void SetFileName(string? value)
        {
            using var valueNative = UTF8Marshaler.CreateInstance(value);
            #if PLATFORM_AnyCPU
            if (Runtime.IsArm64)
            #endif
            #if PLATFORM_arm64 || PLATFORM_AnyCPU
            NativeMethods.ARM64.MagickSettings_SetFileName(Instance, valueNative.Instance);
            #endif
            #if PLATFORM_AnyCPU
            else if (Runtime.Is64Bit)
            #endif
            #if PLATFORM_x64 || PLATFORM_AnyCPU
            NativeMethods.X64.MagickSettings_SetFileName(Instance, valueNative.Instance);
            #endif
            #if PLATFORM_AnyCPU
            else
            #endif
            #if PLATFORM_x86 || PLATFORM_AnyCPU
            NativeMethods.X86.MagickSettings_SetFileName(Instance, valueNative.Instance);
            #endif
        }
        public string? SetFont(string? value)
        {
            using var valueNative = UTF8Marshaler.CreateInstance(value);
            IntPtr result;
            #if PLATFORM_AnyCPU
            if (Runtime.IsArm64)
            #endif
            #if PLATFORM_arm64 || PLATFORM_AnyCPU
            result = NativeMethods.ARM64.MagickSettings_SetFont(Instance, valueNative.Instance);
            #endif
            #if PLATFORM_AnyCPU
            else if (Runtime.Is64Bit)
            #endif
            #if PLATFORM_x64 || PLATFORM_AnyCPU
            result = NativeMethods.X64.MagickSettings_SetFont(Instance, valueNative.Instance);
            #endif
            #if PLATFORM_AnyCPU
            else
            #endif
            #if PLATFORM_x86 || PLATFORM_AnyCPU
            result = NativeMethods.X86.MagickSettings_SetFont(Instance, valueNative.Instance);
            #endif
            return UTF8Marshaler.NativeToManagedNullable(result);
        }
        public void SetNumberScenes(int value)
        {
            #if PLATFORM_AnyCPU
            if (Runtime.IsArm64)
            #endif
            #if PLATFORM_arm64 || PLATFORM_AnyCPU
            NativeMethods.ARM64.MagickSettings_SetNumberScenes(Instance, (UIntPtr)value);
            #endif
            #if PLATFORM_AnyCPU
            else if (Runtime.Is64Bit)
            #endif
            #if PLATFORM_x64 || PLATFORM_AnyCPU
            NativeMethods.X64.MagickSettings_SetNumberScenes(Instance, (UIntPtr)value);
            #endif
            #if PLATFORM_AnyCPU
            else
            #endif
            #if PLATFORM_x86 || PLATFORM_AnyCPU
            NativeMethods.X86.MagickSettings_SetNumberScenes(Instance, (UIntPtr)value);
            #endif
        }
        public void SetOption(string key, string? value)
        {
            using var keyNative = UTF8Marshaler.CreateInstance(key);
            using var valueNative = UTF8Marshaler.CreateInstance(value);
            #if PLATFORM_AnyCPU
            if (Runtime.IsArm64)
            #endif
            #if PLATFORM_arm64 || PLATFORM_AnyCPU
            NativeMethods.ARM64.MagickSettings_SetOption(Instance, keyNative.Instance, valueNative.Instance);
            #endif
            #if PLATFORM_AnyCPU
            else if (Runtime.Is64Bit)
            #endif
            #if PLATFORM_x64 || PLATFORM_AnyCPU
            NativeMethods.X64.MagickSettings_SetOption(Instance, keyNative.Instance, valueNative.Instance);
            #endif
            #if PLATFORM_AnyCPU
            else
            #endif
            #if PLATFORM_x86 || PLATFORM_AnyCPU
            NativeMethods.X86.MagickSettings_SetOption(Instance, keyNative.Instance, valueNative.Instance);
            #endif
        }
        public void SetPage(string? value)
        {
            using var valueNative = UTF8Marshaler.CreateInstance(value);
            #if PLATFORM_AnyCPU
            if (Runtime.IsArm64)
            #endif
            #if PLATFORM_arm64 || PLATFORM_AnyCPU
            NativeMethods.ARM64.MagickSettings_SetPage(Instance, valueNative.Instance);
            #endif
            #if PLATFORM_AnyCPU
            else if (Runtime.Is64Bit)
            #endif
            #if PLATFORM_x64 || PLATFORM_AnyCPU
            NativeMethods.X64.MagickSettings_SetPage(Instance, valueNative.Instance);
            #endif
            #if PLATFORM_AnyCPU
            else
            #endif
            #if PLATFORM_x86 || PLATFORM_AnyCPU
            NativeMethods.X86.MagickSettings_SetPage(Instance, valueNative.Instance);
            #endif
        }
        public void SetPing(bool value)
        {
            #if PLATFORM_AnyCPU
            if (Runtime.IsArm64)
            #endif
            #if PLATFORM_arm64 || PLATFORM_AnyCPU
            NativeMethods.ARM64.MagickSettings_SetPing(Instance, value);
            #endif
            #if PLATFORM_AnyCPU
            else if (Runtime.Is64Bit)
            #endif
            #if PLATFORM_x64 || PLATFORM_AnyCPU
            NativeMethods.X64.MagickSettings_SetPing(Instance, value);
            #endif
            #if PLATFORM_AnyCPU
            else
            #endif
            #if PLATFORM_x86 || PLATFORM_AnyCPU
            NativeMethods.X86.MagickSettings_SetPing(Instance, value);
            #endif
        }
        public void SetQuality(int value)
        {
            #if PLATFORM_AnyCPU
            if (Runtime.IsArm64)
            #endif
            #if PLATFORM_arm64 || PLATFORM_AnyCPU
            NativeMethods.ARM64.MagickSettings_SetQuality(Instance, (UIntPtr)value);
            #endif
            #if PLATFORM_AnyCPU
            else if (Runtime.Is64Bit)
            #endif
            #if PLATFORM_x64 || PLATFORM_AnyCPU
            NativeMethods.X64.MagickSettings_SetQuality(Instance, (UIntPtr)value);
            #endif
            #if PLATFORM_AnyCPU
            else
            #endif
            #if PLATFORM_x86 || PLATFORM_AnyCPU
            NativeMethods.X86.MagickSettings_SetQuality(Instance, (UIntPtr)value);
            #endif
        }
        public void SetScenes(string? value)
        {
            using var valueNative = UTF8Marshaler.CreateInstance(value);
            #if PLATFORM_AnyCPU
            if (Runtime.IsArm64)
            #endif
            #if PLATFORM_arm64 || PLATFORM_AnyCPU
            NativeMethods.ARM64.MagickSettings_SetScenes(Instance, valueNative.Instance);
            #endif
            #if PLATFORM_AnyCPU
            else if (Runtime.Is64Bit)
            #endif
            #if PLATFORM_x64 || PLATFORM_AnyCPU
            NativeMethods.X64.MagickSettings_SetScenes(Instance, valueNative.Instance);
            #endif
            #if PLATFORM_AnyCPU
            else
            #endif
            #if PLATFORM_x86 || PLATFORM_AnyCPU
            NativeMethods.X86.MagickSettings_SetScenes(Instance, valueNative.Instance);
            #endif
        }
        public void SetScene(int value)
        {
            #if PLATFORM_AnyCPU
            if (Runtime.IsArm64)
            #endif
            #if PLATFORM_arm64 || PLATFORM_AnyCPU
            NativeMethods.ARM64.MagickSettings_SetScene(Instance, (UIntPtr)value);
            #endif
            #if PLATFORM_AnyCPU
            else if (Runtime.Is64Bit)
            #endif
            #if PLATFORM_x64 || PLATFORM_AnyCPU
            NativeMethods.X64.MagickSettings_SetScene(Instance, (UIntPtr)value);
            #endif
            #if PLATFORM_AnyCPU
            else
            #endif
            #if PLATFORM_x86 || PLATFORM_AnyCPU
            NativeMethods.X86.MagickSettings_SetScene(Instance, (UIntPtr)value);
            #endif
        }
        public void SetSize(string? value)
        {
            using var valueNative = UTF8Marshaler.CreateInstance(value);
            #if PLATFORM_AnyCPU
            if (Runtime.IsArm64)
            #endif
            #if PLATFORM_arm64 || PLATFORM_AnyCPU
            NativeMethods.ARM64.MagickSettings_SetSize(Instance, valueNative.Instance);
            #endif
            #if PLATFORM_AnyCPU
            else if (Runtime.Is64Bit)
            #endif
            #if PLATFORM_x64 || PLATFORM_AnyCPU
            NativeMethods.X64.MagickSettings_SetSize(Instance, valueNative.Instance);
            #endif
            #if PLATFORM_AnyCPU
            else
            #endif
            #if PLATFORM_x86 || PLATFORM_AnyCPU
            NativeMethods.X86.MagickSettings_SetSize(Instance, valueNative.Instance);
            #endif
        }
    }
    internal static INativeInstance CreateInstance(IMagickSettings<QuantumType>? instance)
    {
        if (instance is null)
            return NativeInstance.Zero;
        return MagickSettings.CreateNativeInstance(instance);
    }
}
