#!/bin/sh
set -e

cd "$(dirname "$0")"

export GH_TOKEN=$(cat ../../keys/github.txt)

./install.metadata.sh

versionLine=$(grep -m1 '^- ImageMagick ' metadata/libraries.md)
imageMagickVersion=$(printf '%s' "$versionLine" | sed -E 's/^- (ImageMagick [^)]+\)).*/\1/')

fileName=TrademarkAttribute.cs
printf '// <auto-generated/>\n[assembly: System.Reflection.AssemblyTrademark("%s")]\n' "$imageMagickVersion" > $fileName

for architecture in x86 x64 arm64; do
    for quantum in Q8 Q16 Q16-HDRI; do
        ./install.resources.sh $architecture $quantum
    done
done
