using System.Collections;

namespace ImageMagick
{
    /// <summary>
    /// Class that can be used to provide a definition of ExifValues within an EXIF profile.
    /// </summary>
    public class ExifDefinition
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExifDefinition"/> class.
        /// </summary>
        /// <param name="exifTag"></param>
        /// <param name="exifDataType"></param>
        /// <param name="isArray"></param>
        internal ExifDefinition(ExifTag exifTag, ExifDataType exifDataType, bool isArray)
        {
            ExifTag = exifTag;
            ExifDataType = exifDataType;
            IsArray = isArray;
        }

        /// <summary>
        /// Gets a value indicating ExifTag for the current definition.
        /// </summary>
        public ExifTag ExifTag
        {
            get; 
            private set;
        }

        /// <summary>
        /// Gets a value indicating ExifDataType for the current definition.
        /// </summary>
        public ExifDataType ExifDataType 
        {
            get; 
            private set;
        }

        /// <summary>
        /// Gets a value indicating whether current definition contains an array value.
        /// </summary>
        public bool IsArray 
        {
            get; 
            private set;
        }

        public static Hashtable ExifDefinitions { get; } = new Hashtable
        {
            { ExifTag.SubfileType, new ExifDefinition(ExifTag.SubfileType, ExifDataType.Short, false) },
            { ExifTag.OldSubfileType, new ExifDefinition(ExifTag.SubfileType, ExifDataType.Short, false) },
            { ExifTag.ImageWidth, new ExifDefinition(ExifTag.ImageWidth, ExifDataType.Long, false) },
            { ExifTag.ImageLength, new ExifDefinition(ExifTag.ImageLength, ExifDataType.Long, false) },
            { ExifTag.BitsPerSample, new ExifDefinition(ExifTag.BitsPerSample, ExifDataType.Short, false) },
            { ExifTag.Compression, new ExifDefinition(ExifTag.Compression, ExifDataType.Short, false) },
            { ExifTag.PhotometricInterpretation, new ExifDefinition(ExifTag.PhotometricInterpretation, ExifDataType.Short, false) },
            { ExifTag.Thresholding, new ExifDefinition(ExifTag.Thresholding, ExifDataType.Short, false) },
            { ExifTag.CellWidth, new ExifDefinition(ExifTag.CellWidth, ExifDataType.Short, false) },
            { ExifTag.CellLength, new ExifDefinition(ExifTag.CellLength, ExifDataType.Short, false) },
            { ExifTag.FillOrder, new ExifDefinition(ExifTag.FillOrder, ExifDataType.Short, false) },
            { ExifTag.DocumentName, new ExifDefinition(ExifTag.DocumentName, ExifDataType.Ascii, false) },
            { ExifTag.ImageDescription, new ExifDefinition(ExifTag.ImageDescription, ExifDataType.Ascii, false) },
            { ExifTag.Make, new ExifDefinition(ExifTag.Make, ExifDataType.Ascii, false) },
            { ExifTag.Model, new ExifDefinition(ExifTag.Model, ExifDataType.Ascii, false) },
            { ExifTag.StripOffsets, new ExifDefinition(ExifTag.StripOffsets, ExifDataType.Long, false) },
            { ExifTag.Orientation, new ExifDefinition(ExifTag.Orientation, ExifDataType.Short, false) },
            { ExifTag.SamplesPerPixel, new ExifDefinition(ExifTag.SamplesPerPixel, ExifDataType.Short, false) },
            { ExifTag.RowsPerStrip, new ExifDefinition(ExifTag.RowsPerStrip, ExifDataType.Long, false) },
            { ExifTag.StripByteCounts, new ExifDefinition(ExifTag.StripByteCounts, ExifDataType.Long, false) },
            { ExifTag.XResolution, new ExifDefinition(ExifTag.XResolution, ExifDataType.Rational, false) },
            { ExifTag.YResolution, new ExifDefinition(ExifTag.YResolution, ExifDataType.Rational, false) },
            { ExifTag.PlanarConfiguration, new ExifDefinition(ExifTag.PlanarConfiguration, ExifDataType.Short, false) },
            { ExifTag.GrayResponseUnit, new ExifDefinition(ExifTag.GrayResponseUnit, ExifDataType.Short, false) },
            { ExifTag.GrayResponseCurve, new ExifDefinition(ExifTag.GrayResponseCurve, ExifDataType.Short, false) },
            { ExifTag.T4Options, new ExifDefinition(ExifTag.T4Options, ExifDataType.Long, false) },
            { ExifTag.T6Options, new ExifDefinition(ExifTag.T6Options, ExifDataType.Long, false) },
            { ExifTag.ResolutionUnit, new ExifDefinition(ExifTag.ResolutionUnit, ExifDataType.Short, false) },
            { ExifTag.PageNumber, new ExifDefinition(ExifTag.PageNumber, ExifDataType.Short, false) },
            { ExifTag.TransferFunction, new ExifDefinition(ExifTag.TransferFunction, ExifDataType.Short, false) },
            { ExifTag.Software, new ExifDefinition(ExifTag.Software, ExifDataType.Ascii, false) },
            { ExifTag.DateTime, new ExifDefinition(ExifTag.DateTime, ExifDataType.Ascii, false) },
            { ExifTag.Artist, new ExifDefinition(ExifTag.Artist, ExifDataType.Ascii, false) },
            { ExifTag.HostComputer, new ExifDefinition(ExifTag.HostComputer, ExifDataType.Ascii, false) },
            { ExifTag.Predictor, new ExifDefinition(ExifTag.Predictor, ExifDataType.Short, false) },
            { ExifTag.WhitePoint, new ExifDefinition(ExifTag.WhitePoint, ExifDataType.Rational, false) },
            { ExifTag.PrimaryChromaticities, new ExifDefinition(ExifTag.PrimaryChromaticities, ExifDataType.Rational, false) },
            { ExifTag.ColorMap, new ExifDefinition(ExifTag.ColorMap, ExifDataType.Short, false) },
            { ExifTag.HalftoneHints, new ExifDefinition(ExifTag.HalftoneHints, ExifDataType.Short, false) },
            { ExifTag.TileWidth, new ExifDefinition(ExifTag.TileWidth, ExifDataType.Short, false) },
            { ExifTag.TileLength, new ExifDefinition(ExifTag.TileLength, ExifDataType.Short, false) },
            { ExifTag.TileOffsets, new ExifDefinition(ExifTag.TileOffsets, ExifDataType.Short, false) },
            { ExifTag.TileByteCounts, new ExifDefinition(ExifTag.TileByteCounts, ExifDataType.Short, false) },
            //{ ExifTag.SubIFDs, new ExifDefinition(ExifTag.SubIFDs, ExifDataType.Long, false) },
            { ExifTag.InkSet, new ExifDefinition(ExifTag.InkSet, ExifDataType.Short, false) },
            { ExifTag.InkNames, new ExifDefinition(ExifTag.InkNames, ExifDataType.Ascii, false) },
            { ExifTag.NumberOfInks, new ExifDefinition(ExifTag.NumberOfInks, ExifDataType.Short, false) },
            { ExifTag.DotRange, new ExifDefinition(ExifTag.DotRange, ExifDataType.Byte, false) },
            { ExifTag.TargetPrinter, new ExifDefinition(ExifTag.TargetPrinter, ExifDataType.Ascii, false) },
            { ExifTag.ExtraSamples, new ExifDefinition(ExifTag.ExtraSamples, ExifDataType.Short, false) },
            { ExifTag.SampleFormat, new ExifDefinition(ExifTag.SampleFormat, ExifDataType.Short, false) },
            { ExifTag.SMinSampleValue, new ExifDefinition(ExifTag.SMinSampleValue, ExifDataType.Short, false) },
            { ExifTag.SMaxSampleValue, new ExifDefinition(ExifTag.SMaxSampleValue, ExifDataType.Short, false) },
            { ExifTag.TransferRange, new ExifDefinition(ExifTag.TransferRange, ExifDataType.Short, false) },
            { ExifTag.ClipPath, new ExifDefinition(ExifTag.ClipPath, ExifDataType.Byte, false) },
            { ExifTag.XClipPathUnits, new ExifDefinition(ExifTag.XClipPathUnits, ExifDataType.SignedShort, false) },
            { ExifTag.YClipPathUnits, new ExifDefinition(ExifTag.YClipPathUnits, ExifDataType.SignedShort, false) },
            { ExifTag.Indexed, new ExifDefinition(ExifTag.Indexed, ExifDataType.Short, false) },
            { ExifTag.JPEGTables, new ExifDefinition(ExifTag.JPEGTables, ExifDataType.Undefined, false) },
            { ExifTag.OPIProxy, new ExifDefinition(ExifTag.OPIProxy, ExifDataType.Short, false) },
            { ExifTag.JPEGProc, new ExifDefinition(ExifTag.JPEGProc, ExifDataType.Long, false) },
            { ExifTag.JPEGInterchangeFormat, new ExifDefinition(ExifTag.JPEGInterchangeFormat, ExifDataType.Long, false) },
            { ExifTag.JPEGInterchangeFormatLength, new ExifDefinition(ExifTag.JPEGInterchangeFormatLength, ExifDataType.Long, false) },
            { ExifTag.JPEGRestartInterval, new ExifDefinition(ExifTag.JPEGRestartInterval, ExifDataType.Short, false) },
            { ExifTag.JPEGLosslessPredictors, new ExifDefinition(ExifTag.JPEGLosslessPredictors, ExifDataType.Short, false) },
            { ExifTag.JPEGPointTransforms, new ExifDefinition(ExifTag.JPEGPointTransforms, ExifDataType.Short, false) },
            { ExifTag.JPEGQTables, new ExifDefinition(ExifTag.JPEGQTables, ExifDataType.Long, false) },
            { ExifTag.JPEGDCTables, new ExifDefinition(ExifTag.JPEGDCTables, ExifDataType.Long, false) },
            { ExifTag.JPEGACTables, new ExifDefinition(ExifTag.JPEGACTables, ExifDataType.Long, false) },
            { ExifTag.YCbCrCoefficients, new ExifDefinition(ExifTag.YCbCrCoefficients, ExifDataType.Rational, false) },
            { ExifTag.YCbCrSubsampling, new ExifDefinition(ExifTag.YCbCrSubsampling, ExifDataType.Short, false) },
            { ExifTag.YCbCrPositioning, new ExifDefinition(ExifTag.YCbCrPositioning, ExifDataType.Short, false) },
            { ExifTag.ReferenceBlackWhite, new ExifDefinition(ExifTag.ReferenceBlackWhite, ExifDataType.Rational, false) },
            //{ ExifTag.XMLPacket, new ExifDefinition(ExifTag.XMLPacket, ExifDataType.Byte, false) },
            { ExifTag.Rating, new ExifDefinition(ExifTag.Rating, ExifDataType.Short, false) },
            { ExifTag.RatingPercent, new ExifDefinition(ExifTag.RatingPercent, ExifDataType.Short, false) },
            { ExifTag.ImageID, new ExifDefinition(ExifTag.ImageID, ExifDataType.Ascii, false) },
            { ExifTag.CFARepeatPatternDim, new ExifDefinition(ExifTag.CFARepeatPatternDim, ExifDataType.Short, false) },
            { ExifTag.CFAPattern, new ExifDefinition(ExifTag.CFAPattern, ExifDataType.Byte, false) },
            { ExifTag.BatteryLevel, new ExifDefinition(ExifTag.BatteryLevel, ExifDataType.Rational, false) },
            { ExifTag.Copyright, new ExifDefinition(ExifTag.Copyright, ExifDataType.Ascii, false) },
            { ExifTag.ExposureTime, new ExifDefinition(ExifTag.ExposureTime, ExifDataType.Rational, false) },
            { ExifTag.FNumber, new ExifDefinition(ExifTag.FNumber, ExifDataType.Rational, false) },
            //{ ExifTag.IPTCNAA, new ExifDefinition(ExifTag.IPTCNAA, ExifDataType.Long, false) },
            //{ ExifTag.ImageResources, new ExifDefinition(ExifTag.ImageResources, ExifDataType.Byte, false) },
            //{ ExifTag.ExifTag, new ExifDefinition(ExifTag.ExifTag, ExifDataType.Long, false) },
            //{ ExifTag.InterColorProfile, new ExifDefinition(ExifTag.InterColorProfile, ExifDataType.Undefined, false) },
            { ExifTag.ExposureProgram, new ExifDefinition(ExifTag.ExposureProgram, ExifDataType.Short, false) },
            { ExifTag.SpectralSensitivity, new ExifDefinition(ExifTag.SpectralSensitivity, ExifDataType.Ascii, false) },
            //{ ExifTag.GPSTag, new ExifDefinition(ExifTag.GPSTag, ExifDataType.Long, false) },
            { ExifTag.ISOSpeedRatings, new ExifDefinition(ExifTag.ISOSpeedRatings, ExifDataType.Short, false) },
            { ExifTag.OECF, new ExifDefinition(ExifTag.OECF, ExifDataType.Undefined, false) },
            { ExifTag.Interlace, new ExifDefinition(ExifTag.Interlace, ExifDataType.Short, false) },
            { ExifTag.TimeZoneOffset, new ExifDefinition(ExifTag.TimeZoneOffset, ExifDataType.SignedShort, false) },
            { ExifTag.SelfTimerMode, new ExifDefinition(ExifTag.SelfTimerMode, ExifDataType.Short, false) },
            { ExifTag.DateTimeOriginal, new ExifDefinition(ExifTag.DateTimeOriginal, ExifDataType.Ascii, false) },
            { ExifTag.CompressedBitsPerPixel, new ExifDefinition(ExifTag.CompressedBitsPerPixel, ExifDataType.Rational, false) },
            { ExifTag.ShutterSpeedValue, new ExifDefinition(ExifTag.ShutterSpeedValue, ExifDataType.SignedRational, false) },
            { ExifTag.ApertureValue, new ExifDefinition(ExifTag.ApertureValue, ExifDataType.Rational, false) },
            { ExifTag.BrightnessValue, new ExifDefinition(ExifTag.BrightnessValue, ExifDataType.SignedRational, false) },
            { ExifTag.ExposureBiasValue, new ExifDefinition(ExifTag.ExposureBiasValue, ExifDataType.SignedRational, false) },
            { ExifTag.MaxApertureValue, new ExifDefinition(ExifTag.MaxApertureValue, ExifDataType.Rational, false) },
            { ExifTag.SubjectDistance, new ExifDefinition(ExifTag.SubjectDistance, ExifDataType.SignedRational, false) },
            { ExifTag.MeteringMode, new ExifDefinition(ExifTag.MeteringMode, ExifDataType.Short, false) },
            { ExifTag.LightSource, new ExifDefinition(ExifTag.LightSource, ExifDataType.Short, false) },
            { ExifTag.Flash, new ExifDefinition(ExifTag.Flash, ExifDataType.Short, false) },
            { ExifTag.FocalLength, new ExifDefinition(ExifTag.FocalLength, ExifDataType.Rational, false) },
            { ExifTag.FlashEnergy, new ExifDefinition(ExifTag.FlashEnergy, ExifDataType.Rational, false) },
            { ExifTag.SpatialFrequencyResponse, new ExifDefinition(ExifTag.SpatialFrequencyResponse, ExifDataType.Undefined, false) },
            { ExifTag.Noise, new ExifDefinition(ExifTag.Noise, ExifDataType.Undefined, false) },
            { ExifTag.FocalPlaneXResolution, new ExifDefinition(ExifTag.FocalPlaneXResolution, ExifDataType.Rational, false) },
            { ExifTag.FocalPlaneYResolution, new ExifDefinition(ExifTag.FocalPlaneYResolution, ExifDataType.Rational, false) },
            { ExifTag.FocalPlaneResolutionUnit, new ExifDefinition(ExifTag.FocalPlaneResolutionUnit, ExifDataType.Short, false) },
            { ExifTag.ImageNumber, new ExifDefinition(ExifTag.ImageNumber, ExifDataType.Long, false) },
            { ExifTag.SecurityClassification, new ExifDefinition(ExifTag.SecurityClassification, ExifDataType.Ascii, false) },
            { ExifTag.ImageHistory, new ExifDefinition(ExifTag.ImageHistory, ExifDataType.Ascii, false) },
            { ExifTag.SubjectLocation, new ExifDefinition(ExifTag.SubjectLocation, ExifDataType.Short, false) },
            { ExifTag.ExposureIndex, new ExifDefinition(ExifTag.ExposureIndex, ExifDataType.Rational, false) },
            { ExifTag.TIFFEPStandardID, new ExifDefinition(ExifTag.TIFFEPStandardID, ExifDataType.Byte, false) },
            { ExifTag.SensingMethod, new ExifDefinition(ExifTag.SensingMethod, ExifDataType.Short, false) },
            { ExifTag.XPTitle, new ExifDefinition(ExifTag.XPTitle, ExifDataType.Byte, false) },
            { ExifTag.XPComment, new ExifDefinition(ExifTag.XPComment, ExifDataType.Byte, false) },
            { ExifTag.XPAuthor, new ExifDefinition(ExifTag.XPAuthor, ExifDataType.Byte, false) },
            { ExifTag.XPKeywords, new ExifDefinition(ExifTag.XPKeywords, ExifDataType.Byte, false) },
            { ExifTag.XPSubject, new ExifDefinition(ExifTag.XPSubject, ExifDataType.Byte, false) },
            //{ ExifTag.PrintImageMatching, new ExifDefinition(ExifTag.PrintImageMatching, ExifDataType.Undefined, false) },
            //{ ExifTag.DNGVersion, new ExifDefinition(ExifTag.DNGVersion, ExifDataType.Byte, false) },
            //{ ExifTag.DNGBackwardVersion, new ExifDefinition(ExifTag.DNGBackwardVersion, ExifDataType.Byte, false) },
            //{ ExifTag.UniqueCameraModel, new ExifDefinition(ExifTag.UniqueCameraModel, ExifDataType.Ascii, false) },
            //{ ExifTag.LocalizedCameraModel, new ExifDefinition(ExifTag.LocalizedCameraModel, ExifDataType.Byte, false) },
            //{ ExifTag.CFAPlaneColor, new ExifDefinition(ExifTag.CFAPlaneColor, ExifDataType.Byte, false) },
            //{ ExifTag.CFALayout, new ExifDefinition(ExifTag.CFALayout, ExifDataType.Short, false) },
            //{ ExifTag.LinearizationTable, new ExifDefinition(ExifTag.LinearizationTable, ExifDataType.Short, false) },
            //{ ExifTag.BlackLevelRepeatDim, new ExifDefinition(ExifTag.BlackLevelRepeatDim, ExifDataType.Short, false) },
            //{ ExifTag.BlackLevel, new ExifDefinition(ExifTag.BlackLevel, ExifDataType.Rational, false) },
            //{ ExifTag.BlackLevelDeltaH, new ExifDefinition(ExifTag.BlackLevelDeltaH, ExifDataType.SignedRational, false) },
            //{ ExifTag.BlackLevelDeltaV, new ExifDefinition(ExifTag.BlackLevelDeltaV, ExifDataType.SignedRational, false) },
            //{ ExifTag.WhiteLevel, new ExifDefinition(ExifTag.WhiteLevel, ExifDataType.Short, false) },
            //{ ExifTag.DefaultScale, new ExifDefinition(ExifTag.DefaultScale, ExifDataType.Rational, false) },
            //{ ExifTag.DefaultCropOrigin, new ExifDefinition(ExifTag.DefaultCropOrigin, ExifDataType.Short, false) },
            //{ ExifTag.DefaultCropSize, new ExifDefinition(ExifTag.DefaultCropSize, ExifDataType.Short, false) },
            //{ ExifTag.ColorMatrix1, new ExifDefinition(ExifTag.ColorMatrix1, ExifDataType.SignedRational, false) },
            //{ ExifTag.ColorMatrix2, new ExifDefinition(ExifTag.ColorMatrix2, ExifDataType.SignedRational, false) },
            //{ ExifTag.CameraCalibration1, new ExifDefinition(ExifTag.CameraCalibration1, ExifDataType.SignedRational, false) },
            //{ ExifTag.CameraCalibration2, new ExifDefinition(ExifTag.CameraCalibration2, ExifDataType.SignedRational, false) },
            //{ ExifTag.ReductionMatrix1, new ExifDefinition(ExifTag.ReductionMatrix1, ExifDataType.SignedRational, false) },
            //{ ExifTag.ReductionMatrix2, new ExifDefinition(ExifTag.ReductionMatrix2, ExifDataType.SignedRational, false) },
            //{ ExifTag.AnalogBalance, new ExifDefinition(ExifTag.AnalogBalance, ExifDataType.Rational, false) },
            //{ ExifTag.AsShotNeutral, new ExifDefinition(ExifTag.AsShotNeutral, ExifDataType.Short, false) },
            //{ ExifTag.AsShotWhiteXY, new ExifDefinition(ExifTag.AsShotWhiteXY, ExifDataType.Rational, false) },
            //{ ExifTag.BaselineExposure, new ExifDefinition(ExifTag.BaselineExposure, ExifDataType.SignedRational, false) },
            //{ ExifTag.BaselineNoise, new ExifDefinition(ExifTag.BaselineNoise, ExifDataType.Rational, false) },
            //{ ExifTag.BaselineSharpness, new ExifDefinition(ExifTag.BaselineSharpness, ExifDataType.Rational, false) },
            //{ ExifTag.BayerGreenSplit, new ExifDefinition(ExifTag.BayerGreenSplit, ExifDataType.Long, false) },
            //{ ExifTag.LinearResponseLimit, new ExifDefinition(ExifTag.LinearResponseLimit, ExifDataType.Rational, false) },
            //{ ExifTag.CameraSerialNumber, new ExifDefinition(ExifTag.CameraSerialNumber, ExifDataType.Ascii, false) },
            { ExifTag.LensInfo, new ExifDefinition(ExifTag.LensInfo, ExifDataType.Rational, false) },
            //{ ExifTag.ChromaBlurRadius, new ExifDefinition(ExifTag.ChromaBlurRadius, ExifDataType.Rational, false) },
            //{ ExifTag.AntiAliasStrength, new ExifDefinition(ExifTag.AntiAliasStrength, ExifDataType.Rational, false) },
            //{ ExifTag.ShadowScale, new ExifDefinition(ExifTag.ShadowScale, ExifDataType.SignedRational, false) },
            //{ ExifTag.DNGPrivateData, new ExifDefinition(ExifTag.DNGPrivateData, ExifDataType.Byte, false) },
            //{ ExifTag.MakerNoteSafety, new ExifDefinition(ExifTag.MakerNoteSafety, ExifDataType.Short, false) },
            //{ ExifTag.CalibrationIlluminant1, new ExifDefinition(ExifTag.CalibrationIlluminant1, ExifDataType.Short, false) },
            //{ ExifTag.CalibrationIlluminant2, new ExifDefinition(ExifTag.CalibrationIlluminant2, ExifDataType.Short, false) },
            //{ ExifTag.BestQualityScale, new ExifDefinition(ExifTag.BestQualityScale, ExifDataType.Rational, false) },
            //{ ExifTag.RawDataUniqueID, new ExifDefinition(ExifTag.RawDataUniqueID, ExifDataType.Byte, false) },
            //{ ExifTag.OriginalRawFileName, new ExifDefinition(ExifTag.OriginalRawFileName, ExifDataType.Byte, false) },
            //{ ExifTag.OriginalRawFileData, new ExifDefinition(ExifTag.OriginalRawFileData, ExifDataType.Undefined, false) },
            //{ ExifTag.ActiveArea, new ExifDefinition(ExifTag.ActiveArea, ExifDataType.Short, false) },
            //{ ExifTag.MaskedAreas, new ExifDefinition(ExifTag.MaskedAreas, ExifDataType.Short, false) },
            //{ ExifTag.AsShotICCProfile, new ExifDefinition(ExifTag.AsShotICCProfile, ExifDataType.Undefined, false) },
            //{ ExifTag.AsShotPreProfileMatrix, new ExifDefinition(ExifTag.AsShotPreProfileMatrix, ExifDataType.SignedRational, false) },
            //{ ExifTag.CurrentICCProfile, new ExifDefinition(ExifTag.CurrentICCProfile, ExifDataType.Undefined, false) },
            //{ ExifTag.CurrentPreProfileMatrix, new ExifDefinition(ExifTag.CurrentPreProfileMatrix, ExifDataType.SignedRational, false) },
            //{ ExifTag.ColorimetricReference, new ExifDefinition(ExifTag.ColorimetricReference, ExifDataType.Short, false) },
            //{ ExifTag.CameraCalibrationSignature, new ExifDefinition(ExifTag.CameraCalibrationSignature, ExifDataType.Byte, false) },
            //{ ExifTag.ProfileCalibrationSignature, new ExifDefinition(ExifTag.ProfileCalibrationSignature, ExifDataType.Byte, false) },
            //{ ExifTag.AsShotProfileName, new ExifDefinition(ExifTag.AsShotProfileName, ExifDataType.Byte, false) },
            //{ ExifTag.NoiseReductionApplied, new ExifDefinition(ExifTag.NoiseReductionApplied, ExifDataType.Rational, false) },
            //{ ExifTag.ProfileName, new ExifDefinition(ExifTag.ProfileName, ExifDataType.Byte, false) },
            //{ ExifTag.ProfileHueSatMapDims, new ExifDefinition(ExifTag.ProfileHueSatMapDims, ExifDataType.Long, false) },
            //{ ExifTag.ProfileHueSatMapData1, new ExifDefinition(ExifTag.ProfileHueSatMapData1, ExifDataType.Float, false) },
            //{ ExifTag.ProfileHueSatMapData2, new ExifDefinition(ExifTag.ProfileHueSatMapData2, ExifDataType.Float, false) },
            //{ ExifTag.ProfileToneCurve, new ExifDefinition(ExifTag.ProfileToneCurve, ExifDataType.Float, false) },
            //{ ExifTag.ProfileEmbedPolicy, new ExifDefinition(ExifTag.ProfileEmbedPolicy, ExifDataType.Long, false) },
            //{ ExifTag.ProfileCopyright, new ExifDefinition(ExifTag.ProfileCopyright, ExifDataType.Byte, false) },
            //{ ExifTag.ForwardMatrix1, new ExifDefinition(ExifTag.ForwardMatrix1, ExifDataType.SignedRational, false) },
            //{ ExifTag.ForwardMatrix2, new ExifDefinition(ExifTag.ForwardMatrix2, ExifDataType.SignedRational, false) },
            //{ ExifTag.PreviewApplicationName, new ExifDefinition(ExifTag.PreviewApplicationName, ExifDataType.Byte, false) },
            //{ ExifTag.PreviewApplicationVersion, new ExifDefinition(ExifTag.PreviewApplicationVersion, ExifDataType.Byte, false) },
            //{ ExifTag.PreviewSettingsName, new ExifDefinition(ExifTag.PreviewSettingsName, ExifDataType.Byte, false) },
            //{ ExifTag.PreviewSettingsDigest, new ExifDefinition(ExifTag.PreviewSettingsDigest, ExifDataType.Byte, false) },
            //{ ExifTag.PreviewColorSpace, new ExifDefinition(ExifTag.PreviewColorSpace, ExifDataType.Long, false) },
            //{ ExifTag.PreviewDateTime, new ExifDefinition(ExifTag.PreviewDateTime, ExifDataType.Ascii, false) },
            //{ ExifTag.RawImageDigest, new ExifDefinition(ExifTag.RawImageDigest, ExifDataType.Undefined, false) },
            //{ ExifTag.OriginalRawFileDigest, new ExifDefinition(ExifTag.OriginalRawFileDigest, ExifDataType.Undefined, false) },
            //{ ExifTag.SubTileBlockSize, new ExifDefinition(ExifTag.SubTileBlockSize, ExifDataType.Long, false) },
            //{ ExifTag.RowInterleaveFactor, new ExifDefinition(ExifTag.RowInterleaveFactor, ExifDataType.Long, false) },
            //{ ExifTag.ProfileLookTableDims, new ExifDefinition(ExifTag.ProfileLookTableDims, ExifDataType.Long, false) },
            //{ ExifTag.ProfileLookTableData, new ExifDefinition(ExifTag.ProfileLookTableData, ExifDataType.Float, false) },
            //{ ExifTag.OpcodeList1, new ExifDefinition(ExifTag.OpcodeList1, ExifDataType.Undefined, false) },
            //{ ExifTag.OpcodeList2, new ExifDefinition(ExifTag.OpcodeList2, ExifDataType.Undefined, false) },
            //{ ExifTag.OpcodeList3, new ExifDefinition(ExifTag.OpcodeList3, ExifDataType.Undefined, false) },
            //{ ExifTag.NoiseProfile, new ExifDefinition(ExifTag.NoiseProfile, ExifDataType.Double, false) },
            { ExifTag.ExposureTime, new ExifDefinition(ExifTag.ExposureTime, ExifDataType.Rational, false) },
            { ExifTag.FNumber, new ExifDefinition(ExifTag.FNumber, ExifDataType.Rational, false) },
            { ExifTag.ExposureProgram, new ExifDefinition(ExifTag.ExposureProgram, ExifDataType.Short, false) },
            { ExifTag.SpectralSensitivity, new ExifDefinition(ExifTag.SpectralSensitivity, ExifDataType.Ascii, false) },
            { ExifTag.ISOSpeedRatings, new ExifDefinition(ExifTag.ISOSpeedRatings, ExifDataType.Short, false) },
            { ExifTag.OECF, new ExifDefinition(ExifTag.OECF, ExifDataType.Undefined, false) },
            { ExifTag.SensitivityType, new ExifDefinition(ExifTag.SensitivityType, ExifDataType.Short, false) },
            { ExifTag.StandardOutputSensitivity, new ExifDefinition(ExifTag.StandardOutputSensitivity, ExifDataType.Long, false) },
            { ExifTag.RecommendedExposureIndex, new ExifDefinition(ExifTag.RecommendedExposureIndex, ExifDataType.Long, false) },
            { ExifTag.ISOSpeed, new ExifDefinition(ExifTag.ISOSpeed, ExifDataType.Long, false) },
            { ExifTag.ISOSpeedLatitudeyyy, new ExifDefinition(ExifTag.ISOSpeedLatitudeyyy, ExifDataType.Long, false) },
            { ExifTag.ISOSpeedLatitudezzz, new ExifDefinition(ExifTag.ISOSpeedLatitudezzz, ExifDataType.Long, false) },
            { ExifTag.ExifVersion, new ExifDefinition(ExifTag.ExifVersion, ExifDataType.Undefined, false) },
            { ExifTag.DateTimeOriginal, new ExifDefinition(ExifTag.DateTimeOriginal, ExifDataType.Ascii, false) },
            { ExifTag.DateTimeDigitized, new ExifDefinition(ExifTag.DateTimeDigitized, ExifDataType.Ascii, false) },
            { ExifTag.ComponentsConfiguration, new ExifDefinition(ExifTag.ComponentsConfiguration, ExifDataType.Undefined, false) },
            { ExifTag.CompressedBitsPerPixel, new ExifDefinition(ExifTag.CompressedBitsPerPixel, ExifDataType.Rational, false) },
            { ExifTag.ShutterSpeedValue, new ExifDefinition(ExifTag.ShutterSpeedValue, ExifDataType.SignedRational, false) },
            { ExifTag.ApertureValue, new ExifDefinition(ExifTag.ApertureValue, ExifDataType.Rational, false) },
            { ExifTag.BrightnessValue, new ExifDefinition(ExifTag.BrightnessValue, ExifDataType.SignedRational, false) },
            { ExifTag.ExposureBiasValue, new ExifDefinition(ExifTag.ExposureBiasValue, ExifDataType.SignedRational, false) },
            { ExifTag.MaxApertureValue, new ExifDefinition(ExifTag.MaxApertureValue, ExifDataType.Rational, false) },
            { ExifTag.SubjectDistance, new ExifDefinition(ExifTag.SubjectDistance, ExifDataType.Rational, false) },
            { ExifTag.MeteringMode, new ExifDefinition(ExifTag.MeteringMode, ExifDataType.Short, false) },
            { ExifTag.LightSource, new ExifDefinition(ExifTag.LightSource, ExifDataType.Short, false) },
            { ExifTag.Flash, new ExifDefinition(ExifTag.Flash, ExifDataType.Short, false) },
            { ExifTag.FocalLength, new ExifDefinition(ExifTag.FocalLength, ExifDataType.Rational, false) },
            { ExifTag.SubjectArea, new ExifDefinition(ExifTag.SubjectArea, ExifDataType.Short, false) },
            { ExifTag.MakerNote, new ExifDefinition(ExifTag.MakerNote, ExifDataType.Undefined, false) },
            { ExifTag.UserComment, new ExifDefinition(ExifTag.UserComment, ExifDataType.Undefined, false) },
            { ExifTag.SubsecTime, new ExifDefinition(ExifTag.SubsecTime, ExifDataType.Ascii, false) },
            { ExifTag.SubsecTimeOriginal, new ExifDefinition(ExifTag.SubsecTimeOriginal, ExifDataType.Ascii, false) },
            { ExifTag.SubsecTimeDigitized, new ExifDefinition(ExifTag.SubsecTimeDigitized, ExifDataType.Ascii, false) },
            { ExifTag.FlashpixVersion, new ExifDefinition(ExifTag.FlashpixVersion, ExifDataType.Undefined, false) },
            { ExifTag.ColorSpace, new ExifDefinition(ExifTag.ColorSpace, ExifDataType.Short, false) },
            { ExifTag.PixelXDimension, new ExifDefinition(ExifTag.PixelXDimension, ExifDataType.Long, false) },
            { ExifTag.PixelYDimension, new ExifDefinition(ExifTag.PixelYDimension, ExifDataType.Long, false) },
            { ExifTag.RelatedSoundFile, new ExifDefinition(ExifTag.RelatedSoundFile, ExifDataType.Ascii, false) },
            //{ ExifTag.InteroperabilityTag, new ExifDefinition(ExifTag.InteroperabilityTag, ExifDataType.Long, false) },
            { ExifTag.FlashEnergy, new ExifDefinition(ExifTag.FlashEnergy, ExifDataType.Rational, false) },
            { ExifTag.SpatialFrequencyResponse, new ExifDefinition(ExifTag.SpatialFrequencyResponse, ExifDataType.Undefined, false) },
            { ExifTag.FocalPlaneXResolution, new ExifDefinition(ExifTag.FocalPlaneXResolution, ExifDataType.Rational, false) },
            { ExifTag.FocalPlaneYResolution, new ExifDefinition(ExifTag.FocalPlaneYResolution, ExifDataType.Rational, false) },
            { ExifTag.FocalPlaneResolutionUnit, new ExifDefinition(ExifTag.FocalPlaneResolutionUnit, ExifDataType.Short, false) },
            { ExifTag.SubjectLocation, new ExifDefinition(ExifTag.SubjectLocation, ExifDataType.Short, false) },
            { ExifTag.ExposureIndex, new ExifDefinition(ExifTag.ExposureIndex, ExifDataType.Rational, false) },
            { ExifTag.SensingMethod, new ExifDefinition(ExifTag.SensingMethod, ExifDataType.Short, false) },
            { ExifTag.FileSource, new ExifDefinition(ExifTag.FileSource, ExifDataType.Undefined, false) },
            { ExifTag.SceneType, new ExifDefinition(ExifTag.SceneType, ExifDataType.Undefined, false) },
            { ExifTag.CFAPattern, new ExifDefinition(ExifTag.CFAPattern, ExifDataType.Undefined, false) },
            { ExifTag.CustomRendered, new ExifDefinition(ExifTag.CustomRendered, ExifDataType.Short, false) },
            { ExifTag.ExposureMode, new ExifDefinition(ExifTag.ExposureMode, ExifDataType.Short, false) },
            { ExifTag.WhiteBalance, new ExifDefinition(ExifTag.WhiteBalance, ExifDataType.Short, false) },
            { ExifTag.DigitalZoomRatio, new ExifDefinition(ExifTag.DigitalZoomRatio, ExifDataType.Rational, false) },
            { ExifTag.FocalLengthIn35mmFilm, new ExifDefinition(ExifTag.FocalLengthIn35mmFilm, ExifDataType.Short, false) },
            { ExifTag.SceneCaptureType, new ExifDefinition(ExifTag.SceneCaptureType, ExifDataType.Short, false) },
            { ExifTag.GainControl, new ExifDefinition(ExifTag.GainControl, ExifDataType.Short, false) },
            { ExifTag.Contrast, new ExifDefinition(ExifTag.Contrast, ExifDataType.Short, false) },
            { ExifTag.Saturation, new ExifDefinition(ExifTag.Saturation, ExifDataType.Short, false) },
            { ExifTag.Sharpness, new ExifDefinition(ExifTag.Sharpness, ExifDataType.Short, false) },
            { ExifTag.DeviceSettingDescription, new ExifDefinition(ExifTag.DeviceSettingDescription, ExifDataType.Undefined, false) },
            { ExifTag.SubjectDistanceRange, new ExifDefinition(ExifTag.SubjectDistanceRange, ExifDataType.Short, false) },
            { ExifTag.ImageUniqueID, new ExifDefinition(ExifTag.ImageUniqueID, ExifDataType.Ascii, false) },
            //{ ExifTag.CameraOwnerName, new ExifDefinition(ExifTag.CameraOwnerName, ExifDataType.Ascii, false) },
            //{ ExifTag.BodySerialNumber, new ExifDefinition(ExifTag.BodySerialNumber, ExifDataType.Ascii, false) },
            //{ ExifTag.LensSpecification, new ExifDefinition(ExifTag.LensSpecification, ExifDataType.Rational, false) },
            { ExifTag.LensMake, new ExifDefinition(ExifTag.LensMake, ExifDataType.Ascii, false) },
            { ExifTag.LensModel, new ExifDefinition(ExifTag.LensModel, ExifDataType.Ascii, false) },
            { ExifTag.LensSerialNumber, new ExifDefinition(ExifTag.LensSerialNumber, ExifDataType.Ascii, false) },
            //{ ExifTag.InteroperabilityIndex, new ExifDefinition(ExifTag.InteroperabilityIndex, ExifDataType.Ascii, false) },
            //{ ExifTag.InteroperabilityVersion, new ExifDefinition(ExifTag.InteroperabilityVersion, ExifDataType.Undefined, false) },
            //{ ExifTag.RelatedImageFileFormat, new ExifDefinition(ExifTag.RelatedImageFileFormat, ExifDataType.Ascii, false) },
            //{ ExifTag.RelatedImageWidth, new ExifDefinition(ExifTag.RelatedImageWidth, ExifDataType.Long, false) },
            //{ ExifTag.RelatedImageLength, new ExifDefinition(ExifTag.RelatedImageLength, ExifDataType.Long, false) },
            { ExifTag.GPSVersionID, new ExifDefinition(ExifTag.GPSVersionID, ExifDataType.Byte, false) },
            { ExifTag.GPSLatitudeRef, new ExifDefinition(ExifTag.GPSLatitudeRef, ExifDataType.Ascii, false) },
            { ExifTag.GPSLatitude, new ExifDefinition(ExifTag.GPSLatitude, ExifDataType.Rational, false) },
            { ExifTag.GPSLongitudeRef, new ExifDefinition(ExifTag.GPSLongitudeRef, ExifDataType.Ascii, false) },
            { ExifTag.GPSLongitude, new ExifDefinition(ExifTag.GPSLongitude, ExifDataType.Rational, false) },
            { ExifTag.GPSAltitudeRef, new ExifDefinition(ExifTag.GPSAltitudeRef, ExifDataType.Byte, false) },
            { ExifTag.GPSAltitude, new ExifDefinition(ExifTag.GPSAltitude, ExifDataType.Rational, false) },
            //{ ExifTag.GPSTimeStamp, new ExifDefinition(ExifTag.GPSTimeStamp, ExifDataType.Rational, false) },
            { ExifTag.GPSTimestamp, new ExifDefinition(ExifTag.GPSTimestamp, ExifDataType.Rational, false) },
            { ExifTag.GPSSatellites, new ExifDefinition(ExifTag.GPSSatellites, ExifDataType.Ascii, false) },
            { ExifTag.GPSStatus, new ExifDefinition(ExifTag.GPSStatus, ExifDataType.Ascii, false) },
            { ExifTag.GPSMeasureMode, new ExifDefinition(ExifTag.GPSMeasureMode, ExifDataType.Ascii, false) },
            { ExifTag.GPSDOP, new ExifDefinition(ExifTag.GPSDOP, ExifDataType.Rational, false) },
            { ExifTag.GPSSpeedRef, new ExifDefinition(ExifTag.GPSSpeedRef, ExifDataType.Ascii, false) },
            { ExifTag.GPSSpeed, new ExifDefinition(ExifTag.GPSSpeed, ExifDataType.Rational, false) },
            { ExifTag.GPSTrackRef, new ExifDefinition(ExifTag.GPSTrackRef, ExifDataType.Ascii, false) },
            { ExifTag.GPSTrack, new ExifDefinition(ExifTag.GPSTrack, ExifDataType.Rational, false) },
            { ExifTag.GPSImgDirectionRef, new ExifDefinition(ExifTag.GPSImgDirectionRef, ExifDataType.Ascii, false) },
            { ExifTag.GPSImgDirection, new ExifDefinition(ExifTag.GPSImgDirection, ExifDataType.Rational, false) },
            { ExifTag.GPSMapDatum, new ExifDefinition(ExifTag.GPSMapDatum, ExifDataType.Ascii, false) },
            { ExifTag.GPSDestLatitudeRef, new ExifDefinition(ExifTag.GPSDestLatitudeRef, ExifDataType.Ascii, false) },
            { ExifTag.GPSDestLatitude, new ExifDefinition(ExifTag.GPSDestLatitude, ExifDataType.Rational, false) },
            { ExifTag.GPSDestLongitudeRef, new ExifDefinition(ExifTag.GPSDestLongitudeRef, ExifDataType.Ascii, false) },
            { ExifTag.GPSDestLongitude, new ExifDefinition(ExifTag.GPSDestLongitude, ExifDataType.Rational, false) },
            { ExifTag.GPSDestBearingRef, new ExifDefinition(ExifTag.GPSDestBearingRef, ExifDataType.Ascii, false) },
            { ExifTag.GPSDestBearing, new ExifDefinition(ExifTag.GPSDestBearing, ExifDataType.Rational, false) },
            { ExifTag.GPSDestDistanceRef, new ExifDefinition(ExifTag.GPSDestDistanceRef, ExifDataType.Ascii, false) },
            { ExifTag.GPSDestDistance, new ExifDefinition(ExifTag.GPSDestDistance, ExifDataType.Rational, false) },
            { ExifTag.GPSProcessingMethod, new ExifDefinition(ExifTag.GPSProcessingMethod, ExifDataType.Undefined, false) },
            { ExifTag.GPSAreaInformation, new ExifDefinition(ExifTag.GPSAreaInformation, ExifDataType.Undefined, false) },
            { ExifTag.GPSDateStamp, new ExifDefinition(ExifTag.GPSDateStamp, ExifDataType.Ascii, false) },
            { ExifTag.GPSDifferential, new ExifDefinition(ExifTag.GPSDifferential, ExifDataType.Short, false) },
        };
    }
}
