on:
  push:
    branches:
    - debug

permissions:
  contents: read
  packages: read

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

name: Main
jobs:
  version:
    name: Set version
    runs-on: ubuntu-24.04
    outputs:
      version: ${{steps.version.outputs.version}}
      commit: ${{steps.version.outputs.commit}}
      publish: ${{steps.version.outputs.publish}}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-tags: true
          persist-credentials: false

      - name: Set version
        id: version
        run: |
          version=$(git describe --exact-match --tags HEAD 2> /dev/null || true)
          publish=false
          if [ -z "$version" ]; then
              version=$(git log -1 --date=format:"0.%Y.%m%d.%H%M" --format="%ad")
          else
              publish=true
          fi
          commit=$(git rev-parse HEAD)

          echo "version=$version" >> $GITHUB_OUTPUT
          echo "version=$version"
          echo "commit=$commit" >> $GITHUB_OUTPUT
          echo "commit=$commit"
          echo "publish=$publish" >> $GITHUB_OUTPUT
          echo "publish=$publish"

  windows_x64:
    name: Windows (${{matrix.quantumName}}, ${{matrix.platformName}})
    runs-on: windows-2025-vs2026
    needs:
      - version

    strategy:
      fail-fast: false
      matrix:
        quantumName: [Q8, Q8-OpenMP, Q16, Q16-OpenMP, Q16-HDRI, Q16-HDRI-OpenMP]
        platformName: [x86, x64, Any CPU]
        exclude:
        - quantumName: Q8-OpenMP
          platformName: x86
        - quantumName: Q16-OpenMP
          platformName: x86
        - quantumName: Q16-HDRI-OpenMP
          platformName: x86
        - quantumName: Q8-OpenMP
          platformName: Any CPU
        - quantumName: Q16-OpenMP
          platformName: Any CPU
        - quantumName: Q16-HDRI-OpenMP
          platformName: Any CPU

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false

      - name: Install dependencies
        run: ./install.dependencies.cmd
        working-directory: build/windows

      - name: Install NuGet
        run: ./install.nuget.cmd
        working-directory: build/windows

      - name: Create nuget.config
        run: ./create-nuget-config.cmd "dlemstra" "${{ secrets.GITHUB_TOKEN }}"
        working-directory: src/Magick.Native

      - name: Install Magick.Native
        run: ./install.cmd
        working-directory: src/Magick.Native

      - name: Build Magick.NET (Test)
        run: ./build.Magick.NET.cmd ${{ matrix.quantumName }} "${{ matrix.platformName }}" Test
        working-directory: build/windows

      - name: Disable WPAD
        run: |
          Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings' -Name AutoDetect -Value 0
          netsh winhttp set proxy proxy-server="direct://" bypass-list="*"
        shell: pwsh

      - name: Start network trace
        run: netsh trace start capture=yes tracefile=${{ github.workspace }}\trace.etl
        shell: pwsh

      - name: Test Magick.NET
        run: ./test.Magick.NET.cmd ${{ matrix.quantumName }} "${{ matrix.platformName }}"
        working-directory: build/windows

      - name: Stop network trace
        if: always()
        run: netsh trace stop
        shell: pwsh

      - name: Upload trace
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trace-${{ matrix.quantumName }}-${{ matrix.platformName }}
          path: trace.etl

      - name: Build Magick.NET (Release)
        run: ./build.Magick.NET.cmd ${{ matrix.quantumName }} "${{ matrix.platformName }}" Release
        working-directory: build/windows

      - name: Create NuGet package
        run: ./publish.cmd ${{ matrix.quantumName }} "${{ matrix.platformName }}" "${{ needs.version.outputs.version }}" "${{ needs.version.outputs.commit }}"
        working-directory: publish

      # - name: Upload library
      #   uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      #   with:
      #     name: Magick.NET-${{ matrix.quantumName }}-${{ matrix.platformName }}
      #     path: publish/output
